### ISSUE TITLE
Dead documentation link

### ISSUE THREAD

**Issue by lhzw** [rook/nfs#26]
**Is this a bug report or feature request?**
* Bug Report

**Deviation from expected behavior:**
Getting Started and Documentation
For installation, deployment, and administration of the NFS storage provider, see our [Documentation](https://rook.io/docs/nfs/master).

**Expected behavior:**
Page can be visited. But page was not found, and this [url](https://rook.github.io/docs/nfs/) didn't work either.
**How to reproduce it (minimal and precise):**

**File(s) to submit**:

* Cluster CR (custom resource), typically called `cluster.yaml`, if necessary
* Operator's logs, if necessary
* Crashing pod(s) logs, if necessary

 To get logs, use `kubectl -n <namespace> logs <pod name>`
When pasting logs, always surround them with backticks or use the `insert code` button from the Github UI.
Read [Github documentation if you need help](https://help.github.com/en/articles/creating-and-highlighting-code-blocks).

**Environment**:
* OS (e.g. from /etc/os-release):
* Kernel (e.g. `uname -a`):
* Cloud provider or hardware configuration:
* Rook version (use `rook version` inside of a Rook Pod):
* Storage backend version (e.g. for ceph do `ceph -v`):
* Kubernetes version (use `kubectl version`):
* Kubernetes cluster type (e.g. Tectonic, GKE, OpenShift):
* Storage backend status (e.g. for Ceph use `ceph health` in the [Rook Ceph toolbox](https://rook.io/docs/rook/master/ceph-toolbox.html)):

**Comment by travisn** [comment]
[This](https://rook.github.io/docs/nfs/latest/) is the correct link, we will get that updated.
